// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJXq3MGJGRnFGz5vXH0v1D0WN5mmJi2s4',
    appId: '1:988614001634:web:ec44a5b92307911005afbb',
    messagingSenderId: '988614001634',
    projectId: 'riderapp-370fa',
    authDomain: 'riderapp-370fa.firebaseapp.com',
    storageBucket: 'riderapp-370fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG5csqIjqUeqBaaB9i6EjU644HO5f-v2I',
    appId: '1:988614001634:android:b3ee53729c95915105afbb',
    messagingSenderId: '988614001634',
    projectId: 'riderapp-370fa',
    storageBucket: 'riderapp-370fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9jIxXoLThYX0a0l7-sGbWXIRhp3xfiCA',
    appId: '1:988614001634:ios:eeaad77e3f80a0e505afbb',
    messagingSenderId: '988614001634',
    projectId: 'riderapp-370fa',
    storageBucket: 'riderapp-370fa.appspot.com',
    iosClientId: '988614001634-fl1c46ln9jecjvng0ti38ii9kpgi9bdn.apps.googleusercontent.com',
    iosBundleId: 'com.example.riderapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9jIxXoLThYX0a0l7-sGbWXIRhp3xfiCA',
    appId: '1:988614001634:ios:177f1cd0647a8a6e05afbb',
    messagingSenderId: '988614001634',
    projectId: 'riderapp-370fa',
    storageBucket: 'riderapp-370fa.appspot.com',
    iosClientId: '988614001634-f57beqv3tjrnomjo6r6tvrc8nmepds33.apps.googleusercontent.com',
    iosBundleId: 'com.example.riderapp.RunnerTests',
  );
}
